### ISSUE TITLE
News articles need proper integration

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/PM-Unofficial#10]
Dynamic news and archiving should be implemented instead of creating static homepages and news articles.

**Comment by tryptech** [comment]
Is a news section necessary considering PM development is dead? Or is it PM news in general rather than development?

**Comment by Kfeavel** [comment]
I was thinking something more dynamic and for general news such as major PM tourney results, big community happenings, etc. If we can also redirect the PM launcher on the wii to our URL, news should show up there again too.
