### ISSUE TITLE
New "Continue" Button

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/PM-Unofficial#13]
When I originally was rebuilding this website, I had plans to support multiple languages like on the original PM website. However, these plans fell through and instead became the EULA page you see today. One of the reminents of this experiment is the "continue" button on the homepage. I tried my best to recreate _something_ in the Project M style, but its still pretty ugly in my opinion. This should be changed in order to create a better presentation. 
(Fun fact: the language select icons are still on the server.)

**Comment by tryptech** [comment]
On it after work.

**Comment by Kfeavel** [comment]
Should we keep the PSD files here on Github as well?

**Comment by tryptech** [comment]
I can put the PSDs, AIs, whatever I end up making. Would you want to put
them in another directory like /src/ or something to avoid clutter?

**Comment by Kfeavel** [comment]
Yeah, lets put them under /src/ on the root directory.

**Comment by Kfeavel** [comment]
@tryptech Any progress on this? Sorry to bug you about it.

**Comment by tryptech** [comment]
My bad. I had the button done, but never got around to adding it in. It should be up now but GitHub is having a problem with the source psd though,

**Comment by Kfeavel** [comment]
Thats fine. We'll figure out how to add that later. Thanks for your help!
