### ISSUE TITLE
Reorder stages based on PM SSS (Complete) & alternate stage previews?

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/PM-Unofficial#14]
All of the stages should be prioritized based on the PM stage selection screen and listed as such in order to show legal stages first. Additionally, stage pages should include an alternate stage preview if necessary (i.e. Bowser's Castle's alternate stage is legal vs. non-legal being default.)

**Comment by Kfeavel** [comment]
I'm going to start working on this soon. Here's an interesting idea though:
Should we include non-official PM stages as alternates as sort of an "honorable mention" sort of deal? We'd link to the content creator's page and include downloads but they would be more like addons than official content. /cc @tryptech

**Comment by tryptech** [comment]
2 questions regarding that:
- Do you mean popular non-official stages like some of the alts on the netplay build?
- How do you plan on including them? Do you want to include them in a separate section or, if they're alternates, as secondary info on the stage page (such as melee battlefield on brawl battlefield)?

**Comment by Kfeavel** [comment]
2 answers:
- Yes, non-official stages such as ones from the brawl-vault (I.e. A stage like "Toy Time Galaxy" which works well and fits into the PM style.)
- I would plan on including them in the same page as the main stage only under an alternate / secondary area under the main info (this could be reworked of course to fit out needs.)

**Comment by Kfeavel** [comment]
Part one of this issue has been completed. The (legal) stages have been reordered to match the 3.6 release SSS.
