### ISSUE TITLE
Fix CSS alignment on stage select page

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/PM-Unofficial#15]
I cannot get 960 to cooperate with me no matter what I try. The formatting is correct, but the content needs to be centered.

**Comment by tryptech** [comment]
Alright, so centered, full-width, and icons enlarged. The actual images were bigger than what was being used so I figured we could size them up. I could also have a border on the images and remove the rounded corners to match the current 3.6 SSS.

**Comment by Kfeavel** [comment]
That would be great! If you need me to help with anything then I'd be happy. I can extract all of the images or capture new ones if you'd like.

**Comment by tryptech** [comment]
I think it's fine, I just need to add a border in the css and everything will be set.

**Comment by Kfeavel** [comment]
Thanks so much man! Sorry for not being able to do that myself. I'm still learning CSS. I've always done more non-web development.
