### ISSUE TITLE
New Website Logo

### ISSUE THREAD

**Issue by Kfeavel** [Kfeavel/PM-Unofficial#8]
It would be nice if someone with Photoshop skills could create a new Project M Unofficial logo using the official one provided in the assets. It would be the same logo with "Unofficial" underneath the PM logo.

**Comment by tryptech** [comment]
Bruh, I'm on it

**Comment by tryptech** [comment]
How's this?
![pmu-logo](https://cloud.githubusercontent.com/assets/654389/16716503/3d00c85e-46cc-11e6-9318-7849d0155993.png)

**Comment by Kfeavel** [comment]
Dude, thats perfect. Thanks!

**Comment by Kfeavel** [comment]
logo2 has been replaced with logo3 (the new, unofficial PM logo) and was issued in commit ffba75fd0fd7533d1f9d5d6fbb87fd1cebd8841f. However, the size of the image could be tweaked to better fit the website format. (Look at the homepage for an example.)

**Comment by tryptech** [comment]
Gotcha, I'll get on it when I can

**Comment by Kfeavel** [comment]
Great job! Thanks for doing that!
